// Generated by CoffeeScript 1.7.1
(function() {
  var one, two;

  one = 1;


  /*
  A multi line comment
  is bested between two lines
  of three hashes each
  Note that the CoffeeScript compiler will convert multiline
  comments to JavaScript multiline comments.
  
  But single line comments are ignored
   */

  two = 2;

}).call(this);
