// Generated by CoffeeScript 1.7.1
(function() {
  var comboObj, decimalNumber, exclusiveRange, falseBool, greeting, heredocExample, inclusiveRange, multi, myObj, myProp1, myProp2, name, nameDoubleQuote, nameSingleQuote, nestedObj, noBool, obj, offBool, onBool, one, reverseRange, secondObj, three, trueBool, two, wholeNumber, yesBool, _ref;

  nameDoubleQuote = "value";

  nameSingleQuote = 'other value';

  name = "Jeremy";

  greeting = "Hello, " + name + "!";

  console.log(greeting);

  multi = "some content some more here and one more line here";

  console.log(multi);

  heredocExample = "this is line 1\nthis is line 2\nand this is a greeting between empty lines\n\n  " + greeting + "\n\n";

  console.log(heredocExample);

  wholeNumber = 123;

  decimalNumber = 123.456;

  trueBool = true;

  falseBool = false;

  yesBool = true;

  noBool = false;

  onBool = true;

  offBool = false;

  inclusiveRange = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  console.log(inclusiveRange);

  exclusiveRange = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];

  console.log(exclusiveRange);

  reverseRange = [20, 19, 18, 17, 16, 15, 14, 13, 12, 11];

  console.log(reverseRange);

  obj = {
    name: "Jeremy",
    job: "Programmer"
  };

  console.log(obj);

  secondObj = {
    name: "Sue",
    job: "UNIX admin"
  };

  myProp1 = "foo";

  myProp2 = "bar";

  myObj = {
    myProp1: myProp1,
    myProp2: myProp2
  };

  console.log(myObj);

  comboObj = {
    myProp1: myProp1,
    favColor: "purple"
  };

  console.log(comboObj);

  nestedObj = {
    myProp1: myProp1,
    favColor: "pink",
    other: {
      myProp1: myProp1
    }
  };

  console.log(nestedObj);

  _ref = ["1", "2", "3"], one = _ref[0], two = _ref[1], three = _ref[2];

}).call(this);
