// Generated by CoffeeScript 1.7.1
(function() {
  var Site, arr, i, j, k, key, obj, obj2, siteName, value, _i, _j, _k, _l, _len, _len1, _len2, _len3, _len4, _m,
    __hasProp = {}.hasOwnProperty;

  arr = ["Nettuts+", "Aeututs+", "Phototuts+", "Psdtuts+", "Cgtuts+", "Mobiletuts+"];

  obj = {
    name: "Nettuts+",
    topic: "Web Development",
    editor: "Jeffrey Way"
  };

  for (_i = 0, _len = arr.length; _i < _len; _i++) {
    siteName = arr[_i];
    console.log(siteName);
  }

  console.log("===========");

  for (i = _j = 0, _len1 = arr.length; _j < _len1; i = ++_j) {
    siteName = arr[i];
    console.log("" + i + ". " + siteName);
  }

  console.log("===========");

  for (j = _k = 0, _len2 = arr.length; _k < _len2; j = ++_k) {
    siteName = arr[j];
    if (siteName.indexOf("P") === 0) {
      console.log("" + j + ". " + siteName);
    }
  }

  console.log("===========");

  for (k = _l = 0, _len3 = arr.length; _l < _len3; k = _l += 2) {
    siteName = arr[k];
    console.log("" + k + ". " + siteName);
  }

  console.log("===========");

  for (_m = 0, _len4 = arr.length; _m < _len4; _m++) {
    siteName = arr[_m];
    console.log(siteName);
  }

  console.log("===========");

  console.log((function() {
    var _len5, _n, _results;
    _results = [];
    for (_n = 0, _len5 = arr.length; _n < _len5; _n++) {
      siteName = arr[_n];
      _results.push(siteName);
    }
    return _results;
  })());

  console.log("===========");

  console.log((function() {
    var _len5, _n, _results;
    _results = [];
    for (_n = 0, _len5 = arr.length; _n < _len5; _n++) {
      siteName = arr[_n];
      _results.push(siteName.length);
    }
    return _results;
  })());

  console.log("===========");

  for (key in obj) {
    value = obj[key];
    console.log("" + key + ": " + value);
  }

  console.log("===========");

  for (key in obj) {
    value = obj[key];
    if (key !== "name") {
      console.log("" + key + ": " + value);
    }
  }

  console.log("===========");

  for (key in obj) {
    if (!__hasProp.call(obj, key)) continue;
    value = obj[key];
    console.log("" + key + ": " + value);
  }

  console.log("===========");

  Site = function(name) {
    return this.name = name;
  };

  Site.prototype.topic = "Web Development";

  obj2 = new Site("Nettuts+");


  /*
  At this point, obj2 has 2 properties:
    1. name, which it received from Site constructor
    2. topic, which it inherited from Site prototype
   */

  for (key in obj2) {
    value = obj2[key];
    console.log("" + key + ": " + value);
  }

  console.log("===========");

  for (key in obj2) {
    if (!__hasProp.call(obj2, key)) continue;
    value = obj2[key];
    console.log("" + key + ": " + value);
  }

  console.log("===========");

  i = 0;

  while (arr[i]) {
    console.log(arr[i]);
    i++;
  }

  console.log("===========");

  i = 0;

  while (!(i === arr.length)) {
    console.log(arr[i]);
    i++;
  }

  console.log("===========");

  i = 0;

  while (i !== arr.length) {
    console.log(arr[i]);
    i++;
  }

  console.log("===========");

  while (i !== arr.length) {
    console.log(arr[i++]);
  }

  i = 0;

  while (true) {
    console.log(arr[i++]);
    if (!(i < arr.length)) {
      break;
    }
  }

}).call(this);
