// Generated by CoffeeScript 1.7.1
(function() {
  var job, name, name2, name3, person, x, _ref, _ref1;

  name = "Jeremy";

  job = "Programmer";

  if (name === "Fred") {
    console.log("name is Fred");
  }

  if (name === "Jeremy") {
    console.log("name is Jeremy");
  }

  if (name !== "Fred") {
    console.log("name isnt Fred");
  }

  if (name !== "Jeremy") {
    console.log("name isnt Jeremy");
  }

  if (!false) {
    console.log("not false");
  }

  if (name === "Jeremy" && job === "Programmer") {
    console.log("Jeremy is a programmer");
  }

  if (name != null) {
    console.log("name exists");
  }

  person = {
    name: "Sara",
    job: "DBA"
  };

  console.log(person != null ? person.name : void 0);

  console.log(person != null ? person.age : void 0);

  console.log(typeof superman !== "undefined" && superman !== null ? superman.realname : void 0);

  console.log(person != null ? (_ref = person.name) != null ? (_ref1 = _ref.firstLetter) != null ? _ref1.somethingElse : void 0 : void 0 : void 0);

  if (name == null) {
    name = "Joe";
  }

  console.log(name);

  name2 = false;

  if (name2 == null) {
    name2 = "Joe";
  }

  console.log(name2);

  name3 = false;

  name3 || (name3 = "Joe");

  console.log(name3);

  x = 4;

  if ((0 <= x && x <= 10)) {
    console.log("" + x + " is between 0 and 10");
  }

}).call(this);
