// Generated by CoffeeScript 1.7.1
(function() {
  var job, name;

  name = "Jeremy";

  job = "Programmer";

  if (name === "Fred") {
    console.log("name is Fred");
  }

  if (name === "Jeremy") {
    console.log("name is Jeremy");
  }

  if (name !== "Fred") {
    console.log("name isnt Fred");
  }

  if (name !== "Jeremy") {
    console.log("name isnt Jeremy");
  }

  if (!false) {
    console.log("not false");
  }

  if (name === "Jeremy" && job === "Programmer") {
    console.log("Jeremy is a programmer");
  }

  if (name != null) {
    console.log("name exists");
  }

}).call(this);
