// Generated by CoffeeScript 1.7.1
(function() {
  var courseTopic2, courseTopic3, root;

  courseTopic2 = 'CoffeeScript2';

  console.log(courseTopic2);

  console.log(this.courseTopic2);

  console.log(window.courseTopic2);

  console.dir(this);

  this.courseTopic2 = courseTopic2;

  console.log(window.courseTopic2);

  courseTopic3 = 'CoffeeScript3';

  (typeof exports !== "undefined" && exports !== null ? exports : window).courseTopic3 = courseTopic3;

  console.log(this.courseTopic3);

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.foo = "bar";

}).call(this);
